### ISSUE TITLE
branch name pattern matching

### ISSUE THREAD

**Issue by tcardlab** [netlify/netlify-toml-rs#1] opened 2019-09-17 16:52 UTC
**Deployable Naming Convention**
Under a particular use-case, hundreds of collaborator branches may be generated at any given time. Only a subset of these may require deployment. Is it possible to use or implement pattern matching in a c.get()?

Then in .toml I can use:
```
[context.'deploy/*']
    command = "build command" 
```
Then, ideally:
whatever-\*-is.myDomain.com

I don't know whether it would make more sense within "Override with branch context environment" or above it (might be redundant?).

**Comment by calavera** [comment] 2019-09-17 19:35
Unfortunately netlify doesn't recognize patterns in context names.

**Comment by calavera** [comment] 2019-09-17 19:41
I'm closing this since the issue is really with the platform, not this library. Feel free to go to https://community.netlify.com. We can track feature requests like this one there.

**Closed as completed by calavera** 2019-09-17 19:41 UTC
